export const GET_USER_SUBSCRIPTION_REQUEST="GET_USER_SUBSCRIPTION_REQUEST";
export const GET_USER_SUBSCRIPTION_SUCCESS="GET_USER_SUBSCRIPTION_SUCCESS";
export const GET_USER_SUBSCRIPTION_FAILURE="GET_USER_SUBSCRIPTION_FAILURE";

export const UPGRADE_SUBSCRIPTION_REQUEST="UPGRADE_SUBSCRIPTION_REQUEST";
export const UPGRADE_SUBSCRIPTION_SUCCESS="UPGRADE_SUBSCRIPTION_SUCCESS";
export const UPGRADE_SUBSCRIPTION_FAILURE="UPGRADE_SUBSCRIPTION_FAILURE";

export const PAY_REQUEST="PAY_REQUEST";
export const PAY_SUCCESS="PAY_SUCCESS";
export const PAY_FAILURE="PAY_FAILURE";