export const GET_COMMENTS_REQUEST="GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS="GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILURE="GET_COMMENTS_FAILURE";

export const CREATE_COMMENT_REQUEST="CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS="CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE="CREATE_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST="DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS="DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE="DELETE_COMMENT_FAILURE";