export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILURE = "GET_MESSAGES_FAILURE";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const GET_CHAT_BY_PROJECT_REQUEST = "GET_CHAT_BY_PROJECT_REQUEST";
export const GET_CHAT_BY_PROJECT_SUCCESS = "GET_CHAT_BY_PROJECT_SUCCESS";
export const GET_CHAT_BY_PROJECT_FAILURE = "GET_CHAT_BY_PROJECT_FAILURE";
