export const GET_PROJECTS_REQUEST="GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS="GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE="GET_PROJECTS_FAILURE";

export const GET_PROJECT_BY_ID_REQUEST="GET_PROJECT_BY_ID_REQUEST";
export const GET_PROJECT_BY_ID_SUCCESS="GET_PROJECT_BY_ID_SUCCESS";
export const GET_PROJECT_BY_ID_FAILURE="GET_PROJECT_BY_ID_FAILURE";

export const CREATE_PROJECT_REQUEST="CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS="CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE="CREATE_PROJECT_FAILURE";

export const SEARCH_PROJECT_REQUEST="SEARCH_PROJECT_REQUEST";
export const SEARCH_PROJECT_SUCCESS="SEARCH_PROJECT_SUCCESS";
export const SEARCH_PROJECT_FAILURE="SEARCH_PROJECT_FAILURE";

export const DELETE_PROJECT_REQUEST="DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS="DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAILURE="DELETE_PROJECT_FAILURE";

export const SEND_PROJECT_INVITATION_REQUEST="SEND_PROJECT_INVITATION_REQUEST";
export const SEND_PROJECT_INVITATION_SUCCESS="SEND_PROJECT_INVITATION_SUCCESS";
export const SEND_PROJECT_INVITATION_FAILURE="SEND_PROJECT_INVITATION_FAILURE";

export const ACCEPT_PROJECT_INVITATION_REQUEST="ACCEPT_PROJECT_INVITATION_REQUEST";
export const ACCEPT_PROJECT_INVITATION_SUCCESS="ACCEPT_PROJECT_INVITATION_SUCCESS";
export const ACCEPT_PROJECT_INVITATION_FAILURE="ACCEPT_PROJECT_INVITATION_FAILURE";
